function allconn = allconnset(n, parskI,parsc, useroptions)

if isempty(parskI)||isempty(parsc)
    parsk = repmat(struct,10);
    parsc = repmat(struct,10);
elseif length(parskI)==1
    warning('**Parsk** is only a 1x1 structure. Was layerdefs not called? This should not happen!')
    parsk = repmat(parskI(1),10);
elseif length(parsc)==1
    warning('**Parsc** is only a 1x1 structure. Was layerdefs not called? This should not happen!')
    parsk = repmat(parsc(1),10);
end
for i=1:length(parskI)
    parsk(i) = parskI(i);
end
%%% not needed for parsc because i didnt decide to call it something
%%% different. also, this structure is needlessly complated. it should be
%%% simplified if this starts to give strange results.
% for i=1:length(parsc)
%     parsk(i) = parskI(i);
% end
allconn_set = {...
    {... %%%% ARCHITECTURE 1
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'gwr2layer',   'gwr',{'vel'},                    'vel',[1 0],parsk(2),'knn',parsc(2),'nodes',useroptions.k}...
    {'gwr3layer',   'gwr',{'gwr1layer'},              'pos',[3 2],parsk(3),'knn',parsc(3),'nodes',useroptions.k}...
    {'gwr4layer',   'gwr',{'gwr2layer'},              'vel',[3 2],parsk(4),'knn',parsc(4),'nodes',useroptions.k}...
    {'gwrSTSlayer', 'gwr',{'gwr3layer','gwr4layer'},  'all',[3 2],parsk(5),'knn',parsc(5),'nodes',useroptions.k}...
    }...
    {...%%%% ARCHITECTURE 2
    {'gng1layer',   'gng',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'gng2layer',   'gng',{'vel'},                    'vel',[1 0],parsk(2),'knn',parsc(2),'nodes',useroptions.k}...
    {'gng3layer',   'gng',{'gng1layer'},              'pos',[3 2],parsk(3),'knn',parsc(3),'nodes',useroptions.k}...
    {'gng4layer',   'gng',{'gng2layer'},              'vel',[3 2],parsk(4),'knn',parsc(4),'nodes',useroptions.k}...
    {'gngSTSlayer', 'gng',{'gng4layer','gng3layer'},  'all',[3 2],parsk(5),'knn',parsc(5),'nodes',useroptions.k}...
    }...
    {...%%%% ARCHITECTURE 3
    {'gng1layer',   'gng',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'gng2layer',   'gng',{'vel'},                    'vel',[1 0],parsk(2),'knn',parsc(2),'nodes',useroptions.k}...
    {'gng3layer',   'gng',{'gng1layer'},              'pos',[3 0],parsk(3),'knn',parsc(3),'nodes',useroptions.k}...
    {'gng4layer',   'gng',{'gng2layer'},              'vel',[3 0],parsk(4),'knn',parsc(4),'nodes',useroptions.k}...
    {'gngSTSlayer', 'gng',{'gng4layer','gng3layer'},  'all',[3 0],parsk(5),'knn',parsc(5),'nodes',useroptions.k}...
    }...
    {...%%%% ARCHITECTURE 4
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'gwr2layer',   'gwr',{'vel'},                    'vel',[1 0],parsk(2),'knn',parsc(2),'nodes',useroptions.k}...
    {'gwr3layer',   'gwr',{'gwr1layer'},              'pos',[3 0],parsk(3),'knn',parsc(3),'nodes',useroptions.k}...
    {'gwr4layer',   'gwr',{'gwr2layer'},              'vel',[3 0],parsk(4),'knn',parsc(4),'nodes',useroptions.k}...
    {'gwrSTSlayer', 'gwr',{'gwr3layer','gwr4layer'},  'all',[3 0],parsk(5),'knn',parsc(5),'nodes',useroptions.k}...
    }...
    {...%%%% ARCHITECTURE 5
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[1 2 3],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'gwr2layer',   'gwr',{'vel'},                    'vel',[1 2 3],parsk(2),'knn',parsc(2),'nodes',useroptions.k}...
    {'gwr3layer',   'gwr',{'gwr1layer'},              'pos',[3 2],parsk(3),'knn',parsc(3),'nodes',useroptions.k}...
    {'gwr4layer',   'gwr',{'gwr2layer'},              'vel',[3 2],parsk(4),'knn',parsc(4),'nodes',useroptions.k}...
    {'gwrSTSlayer', 'gwr',{'gwr3layer','gwr4layer'},  'all',[3 2],parsk(5),'knn',parsc(5),'nodes',useroptions.k}...
    }...
    {...%%%% ARCHITECTURE 6
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[3 4 2],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'gwr2layer',   'gwr',{'vel'},                    'vel',[3 4 2],parsk(2),'knn',parsc(2),'nodes',useroptions.k}...
    {'gwrSTSlayer', 'gwr',{'gwr1layer','gwr2layer'},  'all',[3 2],parsk(3),'knn',parsc(3),'nodes',useroptions.k}...
    }...
    {...%%%% ARCHITECTURE 7
    {'gwr1layer',   'gwr',{'all'},                    'all',[3 2], parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'gwr2layer',   'gwr',{'gwr1layer'},              'all',[3 2], parsk(2),'knn',parsc(2),'nodes',useroptions.k}...
    }...
    {...%%%% ARCHITECTURE 8
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[9 0], parsk(1),'knn',parsc(1),'nodes',useroptions.k}... %% now there is a vector where q used to be, because we have the p overlap variable...
    }...
    {...%%%% ARCHITECTURE 9
    {'gwr1layer',   'gwr',{'pos'},                    'pos',3,parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'gwr2layer',   'gwr',{'vel'},                    'vel',3,parsk(2),'knn',parsc(2),'nodes',useroptions.k}...
    {'gwr3layer',   'gwr',{'gwr1layer'},              'pos',3,parsk(3),'knn',parsc(3),'nodes',useroptions.k}...
    {'gwr4layer',   'gwr',{'gwr2layer'},              'vel',3,parsk(4),'knn',parsc(4),'nodes',useroptions.k}...
    {'gwr5layer',   'gwr',{'gwr3layer'},              'pos',3,parsk(5),'knn',parsc(5),'nodes',useroptions.k}...
    {'gwr6layer',   'gwr',{'gwr4layer'},              'vel',3,parsk(6),'knn',parsc(6),'nodes',useroptions.k}...
    {'gwrSTSlayer', 'gwr',{'gwr6layer','gwr5layer'},  'all',3,parsk(7),'knn',parsc(7),'nodes'}
    }...
    {... %%%% ARCHITECTURE 10
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'gwr2layer',   'gwr',{'vel'},                    'vel',[1 0],parsk(2),'knn',parsc(2),'nodes',useroptions.k}...
    {'gwrSTSlayer', 'gwr',{'gwr1layer','gwr2layer'},  'all',[3 2],parsk(3),'knn',parsc(3),'nodes',useroptions.k}...
    }...
    {... %%%% ARCHITECTURE 11
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[3 2],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'gwr2layer',   'gwr',{'vel'},                    'vel',[3 2],parsk(2),'knn',parsc(2),'nodes',useroptions.k}...
    {'gwr3layer',   'gwr',{'gwr1layer'},              'pos',[3 2],parsk(3),'knn',parsc(3),'nodes',useroptions.k}...
    {'gwr4layer',   'gwr',{'gwr2layer'},              'vel',[3 2],parsk(4),'knn',parsc(4),'nodes',useroptions.k}...
    {'gwrSTSlayer', 'gwr',{'gwr3layer','gwr4layer'},  'all',[1 0],parsk(5),'knn',parsc(5),'nodes',useroptions.k}...
    }...
    {... %%%% ARCHITECTURE 12
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'gwr2layer',   'gwr',{'gwr1layer'},              'pos',[9 0],parsk(2),'knn',parsc(2),'nodes',useroptions.k}...
    }...
    {... %%%% ARCHITECTURE 13
    {'gwr1layer',   'gwr',{'vel'},                    'vel',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'gwr2layer',   'gwr',{'gwr1layer'},              'vel',[9 0],parsk(2),'knn',parsc(2),'nodes',useroptions.k}...
    }...
    {... %%%% ARCHITECTURE 14
    {'gwr1layer',   'gwr',{'vel'},                    'vel',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    }...
    {... %%%% ARCHITECTURE 15
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'gwr2layer',   'gwr',{'vel'},                    'vel',[1 0],parsk(2),'knn',parsc(2),'nodes',useroptions.k}...
    {'gwr3layer',   'gwr',{'gwr1layer'},              'pos',[2 1],parsk(3),'knn',parsc(3),'nodes',useroptions.k}...
    {'gwr4layer',   'gwr',{'gwr2layer'},              'vel',[2 1],parsk(4),'knn',parsc(4),'nodes',useroptions.k}...
    {'gwrSTSlayer', 'gwr',{'gwr3layer','gwr4layer'},  'all',[4 3],parsk(5),'knn',parsc(5),'nodes',useroptions.k}...
    }...
    {... %%%% ARCHITECTURE 16
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    }...
    {... %%%% ARCHITECTURE 17
    {'gwr1layer',   'gwr',{'all'},                    'all',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    }...
    {...%%%% ARCHITECTURE 18
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'gwr2layer',   'gwr',{'vel'},                    'vel',[1 0],parsk(2),'knn',parsc(2),'nodes',useroptions.k}...
    {'gwrSTSlayer', 'gwr',{'gwr1layer','gwr2layer'},  'all',[100 0],parsk(3),'knn',parsc(3),'nodes',useroptions.k}...
    }...
    {...%%%% ARCHITECTURE 19
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'',useroptions.k}...
    {'knn2layer',   'knn',{'gwr1layer'},              'pos',[useroptions.w 0],parsk(2),'svm',parsc(2),'indexes',useroptions.k}...
    }...
    {...%%%% ARCHITECTURE 20
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 11],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 12],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 13],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 14],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 15],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 16],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 17],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 18],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 19],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 21],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    }...
    {...%%%% ARCHITECTURE 21
    {'knn1layer',   'knn',{'pos'},                    'pos',[useroptions.w ceil((useroptions.w)/2)],parsk(1),'knn',parsc(1),'nodes',useroptions.k+ 5}...
    }...
    {...%%%% ARCHITECTURE 22
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +0}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +1}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +2}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +3}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +4}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +5}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +6}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +7}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +8}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +9}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +10}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +11}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +12}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +13}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +14}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +15}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +16}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +17}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +18}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +19}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +20}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +21}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +22}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +23}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +24}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +25}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +26}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +27}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +28}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +29}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +30}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +31}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +32}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +33}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +34}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +35}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +36}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +37}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +38}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +39}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +40}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +41}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +42}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +43}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +44}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +45}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +46}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +47}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +48}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +49}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +50}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +51}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +52}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +53}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +54}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +55}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +56}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +57}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +58}...
%     {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k +59}...
    }...
    {...%%%% ARCHITECTURE 23
    {'gwr1layer',   'knn',{'pos'},                    'pos',[9 0],parsk(1),'svm',parsc(1),'nodes',useroptions.k}...
    }...
    {...%%%% ARCHITECTURE 24
    {'gwr1layer',   'knn',{'pos'},                    'pos',[10 0],parsk(1),'svm',parsc(1),'nodes',useroptions.k}...
    }...
    {...%%%% ARCHITECTURE 25
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes',useroptions.k}...
    }...
    {...%%%% ARCHITECTURE 26
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'',useroptions.k}...
    {'knn2layer',   'knn',{'gwr1layer'},              'pos',[useroptions.w 0],parsk(2),'knn',parsc(2),'indexes',useroptions.k}...
    }...
    };
allconn = allconn_set{n};
end
